### ISSUE TITLE
(Request) Add use of wildcard

### ISSUE THREAD

**Issue by esturniolo** [andreafabrizi/Dropbox-Uploader#177]
Hi.
There is a chance to add wildcards for file for all the commands? Upload, Download, delete, etc?

e.g. 
$dropbox_uploader.sh delete /path/to/my/folder/*.txt

Thanks!

**Comment by heylookltsme** [comment]
@esturniolo I was hoping for the same thing. It looks like the dropbox API still does not support this unfortunately. 

As as alternative, I used the output from `dropbox_uploader.sh list` to loop through the files and execute a delete command on each individual file.

This is fine for me since the folder I'm working with will only ever contain a handful of files, but if the number of files you're working with is huge, then this wouldn't be ideal. It looks like the dropbox API has a [delete_batch](https://www.dropbox.com/developers/documentation/http/documentation#files-delete_batch). Perhaps it would be worth adding support for delete_batch to dropbox_uploader.sh.
