### ISSUE TITLE
Parallelize downloads

### ISSUE THREAD

**Issue by colthreepv** [andreafabrizi/Dropbox-Uploader#243]
I am wondering if it's technically possible to parallelize downloads/uploads, using an option in the command associated with that request.

This will greatly help with directories that haves many small files, that are actually a pain to download/upload

**Comment by jremick** [comment]
I haven't followed all the updates recently so I'm not sure if this has been built in, but months ago we needed this and solved it by using GNU Parallel. That enabled much more parallelising customisation to optimise for different file transfer scenarios on different server resource environments (eg. 100K photos vs 5K video clips). That may be an option for you if it hasn't been built in yet.

**Comment by pzelnip** [comment]
Wouldn't the task be bandwidth limited?  Ie - if you're on a 20Mbps link, is there any difference between downloading one file at 20Mbps or downloading two at 10Mbps each?

**Comment by colthreepv** [comment]
HTTP startup time + script execution time is sometimes longer than download time, that's why it's useful to parallelize.
As an idea it might be possible to create a list of links and then download them with aria2 that haves such functionality.
The same cannot be done with uploads, though.

**Comment by jremick** [comment]
For limited connections, you may only have marginal benefits, but when you're working with servers on 1 Gps up / down it can make a big difference. Dropbox is often the bottleneck, not the server the script is running on. So to maximise use of the server, parallelising large batches of uploads enables making use of the available server bandwidth (otherwise it'd be a small fraction being used if done in serial). 

Here's a basic example use with GNU Parallel, which just feeds a large batch of download URLs to a basic script ("dropbox_script.sh") that downloads via cURL and then uploads to Dropbox (via Dropbox Uploader script). Here it's set to run 20 jobs at a time. 

```cat file_list.txt | parallel --progress -eta -j20 'bash dropbox_script.sh {} Dropbox/destination script.log' ```

We use this method for moving batches of 100+ GB of files (photos, videos, etc) between S3, FTP, private web apps and Dropbox (in both directions). It makes a pretty big difference for us.
