### ISSUE TITLE
Removing the sh extension

### ISSUE THREAD

**Issue by agnibho** [andreafabrizi/Dropbox-Uploader#274]
It might be a good idea to remove the sh extensions from the script names. That way the scripts will resemble Linux commmands and it would probably be easier to type the full name.

**Comment by cjwelborn** [comment]
I symlink my most-used scripts from their current directory (`~/scripts`, `~/clones/appname`) to `~/.local.bin` without the extension. So `./dropbox_uploader.sh` becomes `dropbox_uploader`. I will say that this command name is too long the way it is. The real symlink I created was `dboxupload`, because I am way too lazy to type out the original.

@andreafabrizi, have you given any thought to shortening the command (not the project name)?

**Comment by mkolchin** [comment]
Want to have. New version.

**Comment by andreafabrizi** [comment]
The .sh extension will be kept as it indicate the language of the script, as any other scripting language. In case you prefer not having the extension you can create a symlink.

**Comment by iEFdev** [comment]
@andreafabrizi, Just as a note. There are a lot of programs/scripts that are shell scripts, without extention. Like `autoconf`:

![sh_noext](https://cloud.githubusercontent.com/assets/3958664/12960873/dbdf8416-d03d-11e5-80f3-8323bd94c78f.png)

I think an extension could _signal_ if it's a script or a program, and I see Dropbox-Uploader more as a program. //2¢

So, I'd also prefer to have a script with `.sh` &/or a shorter name perhaps. Like `dropShell` ...maybe `dropUp`? :) … and maybe it should go somewhere inside the standard PATH's as default. Cleaner home folder and shorter command (without full path).

_Just an idea…_
