### ISSUE TITLE
No request to enter "App key" and "secret".

### ISSUE THREAD

**Issue by Adamgithub123** [andreafabrizi/Dropbox-Uploader#314]
Hi,

I get the script by using command "git clone https://github.com/andreafabrizi/Dropbox-Uploader.git". After that I ran "./dropbox_uploader.sh", It prompt me Access Token instead of App Key. Please advise. Thanks.

Hardware: Raspberry pi 3
OS: Raspbian Jessie

**Comment by andreafabrizi** [comment]
Yes, it's correct, with the new version you don't need to enter App key/secret anymore.

**Comment by Adamgithub123** [comment]
thanks. After I added the token keys, it just said the configuration has been saved. I never see any activation URL which need me to copy and paste back to web browser and activate it. Please help.

**Comment by Adamgithub123** [comment]
So how should I do to activate it.

**Comment by andreafabrizi** [comment]
You don't have to. Just copy and past the Access token.

**Comment by Ghaz75** [comment]
Sorry Dear Andrea
Dropbox_uploader does not work for me anymore. With the old version everything was fine. But then I cloned new version from your git. And I deleted the .dropbox_uploder configuration file to configure it using your running script. My dev app was also ok I just generated the new access token from the site and copied it. But since there is no more sharing of secret etc and outh authentication and verification option when I try to upload any file It says 
Couldn't connect to host. 
I tried making it on another raspberry pi but again same problem. I am unable to upload my files anymore. Any suggestions please.
