### ISSUE TITLE
Link returned for a file by SHARE is wrong, points to a parent folder

### ISSUE THREAD

**Issue by exmosis** [andreafabrizi/Dropbox-Uploader#415]
I seem to be getting this intermittently and inconsistently. Every now and then, I'll request the URL for a file, but instead of the URL for the file, I'll get a URL for a directory. 

So far, when this happens, it points to the top-most parent directory - for example, requesting the link for **/path/to/image.jpg** returns a link to **/path**.

It only does it for files that exist - if I request an invalid filename, it tells me the file isn't there.

Any ideas?

**Comment by gresteban** [comment]
Hi,

I'm experiencing the same behavior. I find it to happen when changing the name of the parent directory. Then, the link to the parent directory is reported instead of the actual link to the inner files.

**Comment by gresteban** [comment]
Hi,

I'm experiencing the same behavior. I find it to happen when changing the name of the parent directory. Then, the link to the parent directory is reported instead of the actual link to the inner files.

Still, a very useful utility.
Thanks @andreafabrizi.

**Comment by gresteban** [comment]
Hi,

I'm experiencing the same behavior. I find it to happen when changing the name of the parent directory. Then, the link to the parent directory is reported instead of the actual link to the inner files.

Still, a extremely useful utility. Dropbox should provide this functionality itself. So, thanks a lot @andreafabrizi.

**Comment by exmosis** [comment]
Fixed! Thanks for the update, will close this one.
